/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const EntryId = IDL.Text;
export const Timestamp = IDL.Int;
export const FileEntry = IDL.Record({
  'id' : EntryId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'size' : IDL.Nat,
  'mimeType' : IDL.Text,
  'updatedAt' : Timestamp,
  'category' : IDL.Text,
});
export const VaultEntry = IDL.Record({
  'id' : EntryId,
  'blobRef' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'size' : IDL.Nat,
  'tags' : IDL.Vec(IDL.Text),
  'mimeType' : IDL.Text,
  'updatedAt' : Timestamp,
});

export const idlService = IDL.Service({
  'createFileEntry' : IDL.Func(
      [EntryId, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [FileEntry],
      [],
    ),
  'createVaultEntry' : IDL.Func(
      [
        EntryId,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Vec(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [VaultEntry],
      [],
    ),
  'deleteFileEntry' : IDL.Func([EntryId], [IDL.Bool], []),
  'deleteVaultEntry' : IDL.Func([EntryId], [IDL.Bool], []),
  'getFileEntry' : IDL.Func([EntryId], [IDL.Opt(FileEntry)], ['query']),
  'getVaultEntry' : IDL.Func([EntryId], [IDL.Opt(VaultEntry)], ['query']),
  'listFileEntries' : IDL.Func([], [IDL.Vec(FileEntry)], ['query']),
  'listVaultEntries' : IDL.Func([], [IDL.Vec(VaultEntry)], ['query']),
  'renameFileEntry' : IDL.Func([EntryId, IDL.Text], [IDL.Opt(FileEntry)], []),
  'updateVaultEntry' : IDL.Func(
      [EntryId, IDL.Text, IDL.Vec(IDL.Text), IDL.Opt(IDL.Text)],
      [IDL.Opt(VaultEntry)],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const EntryId = IDL.Text;
  const Timestamp = IDL.Int;
  const FileEntry = IDL.Record({
    'id' : EntryId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'size' : IDL.Nat,
    'mimeType' : IDL.Text,
    'updatedAt' : Timestamp,
    'category' : IDL.Text,
  });
  const VaultEntry = IDL.Record({
    'id' : EntryId,
    'blobRef' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'size' : IDL.Nat,
    'tags' : IDL.Vec(IDL.Text),
    'mimeType' : IDL.Text,
    'updatedAt' : Timestamp,
  });
  
  return IDL.Service({
    'createFileEntry' : IDL.Func(
        [EntryId, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [FileEntry],
        [],
      ),
    'createVaultEntry' : IDL.Func(
        [
          EntryId,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Vec(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [VaultEntry],
        [],
      ),
    'deleteFileEntry' : IDL.Func([EntryId], [IDL.Bool], []),
    'deleteVaultEntry' : IDL.Func([EntryId], [IDL.Bool], []),
    'getFileEntry' : IDL.Func([EntryId], [IDL.Opt(FileEntry)], ['query']),
    'getVaultEntry' : IDL.Func([EntryId], [IDL.Opt(VaultEntry)], ['query']),
    'listFileEntries' : IDL.Func([], [IDL.Vec(FileEntry)], ['query']),
    'listVaultEntries' : IDL.Func([], [IDL.Vec(VaultEntry)], ['query']),
    'renameFileEntry' : IDL.Func([EntryId, IDL.Text], [IDL.Opt(FileEntry)], []),
    'updateVaultEntry' : IDL.Func(
        [EntryId, IDL.Text, IDL.Vec(IDL.Text), IDL.Opt(IDL.Text)],
        [IDL.Opt(VaultEntry)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };