/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type EntryId = string;
export interface FileEntry {
  'id' : EntryId,
  'name' : string,
  'createdAt' : Timestamp,
  'size' : bigint,
  'mimeType' : string,
  'updatedAt' : Timestamp,
  'category' : string,
}
export type Timestamp = bigint;
export interface VaultEntry {
  'id' : EntryId,
  'blobRef' : [] | [string],
  'name' : string,
  'createdAt' : Timestamp,
  'size' : bigint,
  'tags' : Array<string>,
  'mimeType' : string,
  'updatedAt' : Timestamp,
}
export interface _SERVICE {
  'createFileEntry' : ActorMethod<
    [EntryId, string, bigint, string, string],
    FileEntry
  >,
  'createVaultEntry' : ActorMethod<
    [EntryId, string, string, bigint, Array<string>, [] | [string]],
    VaultEntry
  >,
  'deleteFileEntry' : ActorMethod<[EntryId], boolean>,
  'deleteVaultEntry' : ActorMethod<[EntryId], boolean>,
  'getFileEntry' : ActorMethod<[EntryId], [] | [FileEntry]>,
  'getVaultEntry' : ActorMethod<[EntryId], [] | [VaultEntry]>,
  'listFileEntries' : ActorMethod<[], Array<FileEntry>>,
  'listVaultEntries' : ActorMethod<[], Array<VaultEntry>>,
  'renameFileEntry' : ActorMethod<[EntryId, string], [] | [FileEntry]>,
  'updateVaultEntry' : ActorMethod<
    [EntryId, string, Array<string>, [] | [string]],
    [] | [VaultEntry]
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];