/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export type EntryId = string;
export interface VaultEntry {
    id: EntryId;
    blobRef?: string;
    name: string;
    createdAt: Timestamp;
    size: bigint;
    tags: Array<string>;
    mimeType: string;
    updatedAt: Timestamp;
}
export interface FileEntry {
    id: EntryId;
    name: string;
    createdAt: Timestamp;
    size: bigint;
    mimeType: string;
    updatedAt: Timestamp;
    category: string;
}
export interface backendInterface {
    createFileEntry(id: EntryId, name: string, size: bigint, mimeType: string, category: string): Promise<FileEntry>;
    createVaultEntry(id: EntryId, name: string, mimeType: string, size: bigint, tags: Array<string>, blobRef: string | null): Promise<VaultEntry>;
    deleteFileEntry(id: EntryId): Promise<boolean>;
    deleteVaultEntry(id: EntryId): Promise<boolean>;
    getFileEntry(id: EntryId): Promise<FileEntry | null>;
    getVaultEntry(id: EntryId): Promise<VaultEntry | null>;
    listFileEntries(): Promise<Array<FileEntry>>;
    listVaultEntries(): Promise<Array<VaultEntry>>;
    renameFileEntry(id: EntryId, name: string): Promise<FileEntry | null>;
    updateVaultEntry(id: EntryId, name: string, tags: Array<string>, blobRef: string | null): Promise<VaultEntry | null>;
}
import type { EntryId as _EntryId, FileEntry as _FileEntry, Timestamp as _Timestamp, VaultEntry as _VaultEntry } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createFileEntry(arg0: EntryId, arg1: string, arg2: bigint, arg3: string, arg4: string): Promise<FileEntry> {
        if (this.processError) {
            try {
                const result = await this.actor.createFileEntry(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createFileEntry(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async createVaultEntry(arg0: EntryId, arg1: string, arg2: string, arg3: bigint, arg4: Array<string>, arg5: string | null): Promise<VaultEntry> {
        if (this.processError) {
            try {
                const result = await this.actor.createVaultEntry(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg5));
                return from_candid_VaultEntry_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createVaultEntry(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg5));
            return from_candid_VaultEntry_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteFileEntry(arg0: EntryId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFileEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFileEntry(arg0);
            return result;
        }
    }
    async deleteVaultEntry(arg0: EntryId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteVaultEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteVaultEntry(arg0);
            return result;
        }
    }
    async getFileEntry(arg0: EntryId): Promise<FileEntry | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getFileEntry(arg0);
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFileEntry(arg0);
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVaultEntry(arg0: EntryId): Promise<VaultEntry | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getVaultEntry(arg0);
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVaultEntry(arg0);
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async listFileEntries(): Promise<Array<FileEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.listFileEntries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listFileEntries();
            return result;
        }
    }
    async listVaultEntries(): Promise<Array<VaultEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.listVaultEntries();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listVaultEntries();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async renameFileEntry(arg0: EntryId, arg1: string): Promise<FileEntry | null> {
        if (this.processError) {
            try {
                const result = await this.actor.renameFileEntry(arg0, arg1);
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.renameFileEntry(arg0, arg1);
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateVaultEntry(arg0: EntryId, arg1: string, arg2: Array<string>, arg3: string | null): Promise<VaultEntry | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateVaultEntry(arg0, arg1, arg2, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg3));
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateVaultEntry(arg0, arg1, arg2, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg3));
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_VaultEntry_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VaultEntry): VaultEntry {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FileEntry]): FileEntry | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_VaultEntry]): VaultEntry | null {
    return value.length === 0 ? null : from_candid_VaultEntry_n2(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _EntryId;
    blobRef: [] | [string];
    name: string;
    createdAt: _Timestamp;
    size: bigint;
    tags: Array<string>;
    mimeType: string;
    updatedAt: _Timestamp;
}): {
    id: EntryId;
    blobRef?: string;
    name: string;
    createdAt: Timestamp;
    size: bigint;
    tags: Array<string>;
    mimeType: string;
    updatedAt: Timestamp;
} {
    return {
        id: value.id,
        blobRef: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.blobRef)),
        name: value.name,
        createdAt: value.createdAt,
        size: value.size,
        tags: value.tags,
        mimeType: value.mimeType,
        updatedAt: value.updatedAt
    };
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_VaultEntry>): Array<VaultEntry> {
    return value.map((x)=>from_candid_VaultEntry_n2(_uploadFile, _downloadFile, x));
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
